name: Setup docker

description: Configure the docker workflow.

inputs:
  DOCKERHUB_ORGANIZATION_NAME :
    description: "DockerHub organization name"
    required: true
  DOCKERHUB_USERNAME:
    description: "DockerHub username"
    required: true
  DOCKERHUB_TOKEN:
    description: "DockerHub access token"
    required: true
  tag:
    description: "Tag for the image"
    required: true

outputs:
  tags:
    description: "tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    - name: Docker meta:${{ inputs.tag }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.DOCKERHUB_ORGANIZATION_NAME }}/yt-dlp,ghcr.io/${{ github.repository_owner }}/yt-dlp
        flavor: |
          latest=${{ inputs.tag == 'latest' }}
        tags: |
          type=ref,event=tag,enable=${{ inputs.tag == 'alpine' }}
          type=ref,suffix=-${{ inputs.tag }},event=tag
          ${{ inputs.tag }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Create a Access Token and save it as as Actions secret
    # https://hub.docker.com/settings/security
    # DOCKERHUB_USERNAME
    # DOCKERHUB_TOKEN
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    # You may need to manage write and read access of GitHub Actions for repositories in the container settings.
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
